### ISSUE TITLE
Make Output Colorful

### ISSUE THREAD

**Issue by FahadLive** [emisdumb/lily#2]
It would be more beautiful and noticable if the output (The message) was in some kind of gradient. 

Also I believe it would match its name :p

Tip: Run the program at the start of a session to encourage yourself even more :p

**Comment by rabbit-time** [comment]
Thanks for the suggestion! I will get around to implementing some colors in the output at some point <3 just busy life at the moment!

**Comment by FahadLive** [comment]
Oh, Take your time then :)

Im currently learning rust, so I will *try* opening a pull request on this feature when Im comfortable in rust programming.

**Comment by rabbit-time** [comment]
Implemented by c9ae43c
